[package]
name = "mental-poker"
version = "0.1.0"
edition = "2021"

[dependencies]
derivative="2.2"
assert_matches="1.5"
derive_more="0.99"
thiserror="1.0"

[dev-dependencies]
either="1.6"
structopt="0.3"
mockall = "0.11.0"
